import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import { AppUIProvider } from "@/providers/ui-provider";

 
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-slate-900">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="theme-color" content="#030712" />
      </head>
      <body
        className={`${inter.className} antialiased min-h-dvh h-full w-screen dark bg-background text-foreground`}
      >
        <AppUIProvider>
          <div className="min-h-dvh h-full pb-12">
            <main className="max-w-6xl pt-8 px-6 h-full mx-auto">
              {children}
            </main>
          </div>
        </AppUIProvider>
      </body>
    </html>
  );
}